Add platform builds
Add platform builds

Add platform builds

Add platform builds

Fix build

Fix build

diff --git a/.github/workflows/erlang.yml b/.github/workflows/erlang.yml
--- a/.github/workflows/erlang.yml
+++ b/.github/workflows/erlang.yml
@@ -7,24 +7,92 @@ on:
     branches: [ master ]
 
 jobs:
-
-  build:
-
+  linux:
     runs-on: ubuntu-latest
-    name: OTP ${{matrix.otp}}
+    name: OTP ${{ matrix.otp }} ${{ matrix.os }}.${{ matrix.compiler.compiler }}
 
     container:
       image: erlang:${{matrix.otp}}
 
     strategy:
       matrix:
+        os: [ linux ]
+        compiler:
+          - { compiler: GNU-10,  CC: gcc-10,   CXX: g++-10 }
+          - { compiler: GNU-11,  CC: gcc-11,   CXX: g++-11 }
+          - { compiler: LLVM-10, CC: clang-11, CXX: clang++-11 }
+          - { compiler: LLVM-11, CC: clang-11, CXX: clang++-11 }
         otp: ["24.1", "24.2"]
 
     steps:
     - uses: actions/checkout@v2
     - name: OTP Version
-      run:  erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
-    - name: User Name
-      run:  whoami
-    - name: Compile
-      run:  make
+      run:  |
+        erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:format("Version=~s\n", [Version]), halt().' -noshell;
+        make
+
+  macOS:
+    name: OTP ${{ matrix.otp }} ${{ matrix.os }}.${{ matrix.compiler.compiler }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ macos-latest ]
+        compiler:
+          - { compiler: XCode,   CC: cc, CXX: c++ }
+        otp: ["24.1", "24.2"]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install Base Dependencies
+        run: |
+          brew update > /dev/null || true
+          brew tap Homebrew/bundle
+          brew install erlang
+          brew install rebar3
+          #brew bundle --verbose
+      - name: Build
+        env:
+          CC: ${{ matrix.compiler.CC }}
+          CXX: ${{ matrix.compiler.CXX }}
+          SRC_DIR: ${{ github.workspace }}
+          BUILD_DIR: ${{ github.workspace }}/build
+          INSTALL_PREFIX: ${{ github.workspace }}/install
+        run: |
+          erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:format("Version=~s\n", [Version]), halt().' -noshell;
+          make
+
+#  windows-msys2:
+#    name: OTP ${{ matrix.otp }} ${{ matrix.os }}.${{ matrix.msys2.msystem }}.${{ matrix.compiler.compiler }}
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: [ windows-latest ]
+#        msys2:
+#          - { msystem: MINGW64, arch: x86_64 }
+#        compiler:
+#          - { compiler: GNU,  CC: gcc,   CXX: g++ }
+#          - { compiler: LLVM, CC: clang, CXX: clang++ }
+#        otp: ["24.1", "24.2"]
+#    defaults:
+#      run:
+#        shell: msys2 {0}
+#    steps:
+#      - uses: actions/checkout@v2
+#      - uses: msys2/setup-msys2@v2
+#        with:
+#          msystem: ${{ matrix.msys2.msystem }}
+#          install: |
+#            pacman -Ss bash curl git base-devel mingw-w64-${{ matrix.msys2.arch }}-toolchain mingw-w64-${{ matrix.msys2.arch }}-gcc mingw-w64-${{ matrix.msys2.arch }}-clang mingw-w64-${{ matrix.msys2.arch }}-cmake mingw-w64-${{ matrix.msys2.arch }}-ninja mingw-w64-${{ matrix.msys2.arch }}-zlib erlang rebar3
+#          update: true
+#      - name: Build And Test
+#        env:
+#          CC: ${{ matrix.compiler.CC }}
+#          CXX: ${{ matrix.compiler.CXX }}
+#          SRC_DIR: ${{ github.workspace }}
+#          BUILD_DIR: ${{ github.workspace }}/build
+#          INSTALL_PREFIX: ${{ github.workspace }}/install
+#        run: |
+#          erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:format("Version=~s\n", [Version]), halt().' -noshell;
+#          make
+#
